---
- name: create users from csv file
  hosts: all                            #Cette ligne indique à Ansible sur quels hôtes (machines) cette tâche doit être exécutée. Dans ce cas, all signifie que la tâche sera exécutée sur tous les hôtes définis dans votre inventaire Ansible.
  tasks:                                #Cette section définit une liste de tâches qui seront exécutées sur les hôtes ciblés.
   - name: reading the csv file
     read_csv:
      path: user.csv
     register: user_list                #Permet de stocker les données du CSV dans une variable 
     delegate_to: localhost             #Indique que la tâche doit être exécutée sur l'hôte local 

   - name: display user_list data
     debug:
      var: user_list.list

   - name: Creer les comptes utilisateurs    partir des donnees CSV
     user:
       name: "{{ item.name }}"
       shell: "{{ item.shell }}"
       home: "{{ item.home }}"
       groups: "{{ item.groups }}" 
       append: yes                     #Permet d'ajouter l'utilisateur aux groupes existants s'il n'y appartient pas déjà.
       generate_ssh_key: yes           # Génère une clé SSH pour l'utilisateur.
     loop: "{{ user_list.list }}"      # Indique que la tâche doit être exécutée pour chaque élément de la liste user_list.list, c'est-à-dire pour chaque ligne du fichier CSV.

